import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
// import "."
import Index from './home'
// import { Outfit } from 'next/font/google'
import Header from '@/components/common/header/header'
import Footer from '@/components/common/footer/footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Cultural Pioneers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main} `}>
       <Index/>
      </main>
    </>
  )
}
